spring.application.name=demos
#razorpay.key.id=${RAZORPAY_KEY_ID}
#razorpay.key.secret=${RAZORPAY_KEY_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://awssqltier.c1q8wgi48v0v.us-east-1.rds.amazonaws.com:5000/productapplication
spring.datasource.username=admin
spring.datasource.password=adminadmin12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql:true

