spring.application.name=demos
#razorpay.key.id=${RAZORPAY_KEY_ID}
#razorpay.key.secret=${RAZORPAY_KEY_SECRET}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productapplication
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
